/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum CurrencyType {
    USD = 'USD',
    JPY = 'JPY',
    CZK = 'CZK',
    DKK = 'DKK',
    GBP = 'GBP',
    HUF = 'HUF',
    PLN = 'PLN',
    RON = 'RON',
    SEK = 'SEK',
    CHF = 'CHF',
    ISK = 'ISK',
    NOK = 'NOK',
    TRY = 'TRY',
    AUD = 'AUD',
    BRL = 'BRL',
    CAD = 'CAD',
    CNY = 'CNY',
    HKD = 'HKD',
    IDR = 'IDR',
    ILS = 'ILS',
    INR = 'INR',
    KRW = 'KRW',
    MXN = 'MXN',
    MYR = 'MYR',
    NZD = 'NZD',
    PHP = 'PHP',
    SGD = 'SGD',
    THB = 'THB',
    ZAR = 'ZAR',
    EUR = 'EUR',
}
