CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

CREATE TABLE IF NOT EXISTS mytb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    T BIGINT NOT NULL,
    K INT NOT NULL,
    D TEXT NOT NULL
);

SELECT * FROM mytb;

