FROM node:latest as build-phase

RUN mkdir /app

WORKDIR /app

COPY package.json /app

RUN yarn install

COPY . /app

RUN npm run build

FROM nginx:latest

COPY --from=build-phase /app/build /usr/share/nginx/html

COPY --from=build-phase /app/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 5000